server:  
  port: ${PORT:8761}

eureka:
  instance:
    hostname: peer1
    metadataMap:
      zone: zone1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://guest:guest@localhost:8762/eureka/

  
spring:  
  security:
    user:
      name: guest
      password: guest
  
  
  
