eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:  
  port: ${PORT:8080}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:
      - id: combo-service
        uri: lb://COMBO-SERVICE
        predicates:
        - Path= /api/**
        filters:
        - RewritePath= /api/(?<segment>.*), /$\{segment}
       
      - id: catalog-service     
        uri: lb://CATALOG-SERVICE
        predicates:
        - Path= /product/**
        filters:
        - RewritePath= /product/(?<path>.*), /$\{path}  
        
      - id: inventory-service   
        uri: lb://INVENTORY-SERVICE
        predicates:
        - Path= /inventory/**
        filters:
        - RewritePath= /inventory/(?<path>.*), /$\{path}  
