eureka:
  client:
    prefer-same-zone-eureka: true
    service-url:
      defaultZone: http://guest:guest@localhost:8762/eureka, http://guest:guest@localhost:8761/eureka
  instance:
    metadata-map:
      zone: zone2
      
server:  
  port: ${PORT:8081}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:
      - id: customer-service
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path= /customer/**
        filters:
        - RewritePath= /customer/(?<segment>.*), /$\{segment}
       
      - id: booking-service     
        uri: lb://BOOKING-SERVICE
        predicates:
        - Path= /booking/**
        filters:
        - RewritePath= /booking/(?<path>.*), /$\{path}  
        
