
server:
  port: 8080

zuul:
  routes:
    merchandising:
      path: /product/**
      serviceId: merchandising-service      
    comment:
      path: /comment/**      
      serviceId: comment-service
    inventory:
      path: /inventory/**
      serviceId: inventory-service      
    
---

spring:
  profiles: dev
  
  cloud:
    stream: 
      bindings: 
        merchandising:
          destination: merchandising
       
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
    
---

spring:
  profiles: live
  
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka             
