eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:  
  port: ${PORT:8080}
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      routes:
      - id: customer-service
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path= /customer/**
        filters:
        - RewritePath= /customer/(?<segment>.*), /$\{segment}
       
      - id: booking-service     
        uri: lb://BOOKING-SERVICE
        predicates:
        - Path= /booking/**
        filters:
        - RewritePath= /booking/(?<path>.*), /$\{path}  
        
     
