server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka      
          
---

spring:
  profiles: dev
  
  cloud:
    stream: 
      bindings: 
        input:
          destination: merchandising
          content-type: application/json
          
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017
      database: test
               
---
      
spring:
  profiles: live
  
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017
      database: test        
